openapi: 3.0.0
info:
  description: This API receives deliver and pick up orders from an application
  version: '1.0.0'
  title: Order Tracking API
  contact:
    email: hhyungmin@my.bcit.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: application
    description: Orders tracking from food application

paths:
  /orders/delivery:
    get:
      tags:
        - application
      summary: Get the deliver order
      operationId: app.get_deliver_order_tracking
      description: Gets a new delivery order to the system|
      parameters:
        - name: orderTime
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:33'
        - name: orderTimeEnd
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:38'
      responses:
        '201':
          description: Successfully returned a delivery tracking order event
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeliveryOrderTracking'
        '400':
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /orders/pickup:
    get:
      tags:
        - application
      summary: Get the pickup order
      operationId: app.get_pickup_order_tracking
      description: Gets a new pickup order to the system
      parameters:
        - name: orderTime
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:33'
        - name: orderTimeEnd
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:38'
      responses:
        '201':
          description: Successfully returned a delivery tracking order event
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PickupOrderTracking'
        '400':
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    DeliveryOrderTracking:
      required:
        - id
        - total
        - deliveryOrderInfo
        - items
        - orderTime
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        total:
          type: number
          example: 15.32
        deliveryOrderInfo:
          $ref: '#/components/schemas/DeliveryOrderInfo'
        items:
          type: string
          example: 'noodle, rice'
        orderTime:
          type: string
          format: date-time
          example: '2021-08-29 09:12:33'
      type: object

    PickupOrderTracking:
      required:
        - id
        - total
        - pickupOrderInfo
        - items
        - orderTime
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        total:
          type: number
          example: 50.21
        pickupOrderInfo:
          $ref: '#/components/schemas/PickupOrderInfo'
        items:
          type: string
          example: 'noodle, rice'
        orderTime:
          type: string
          format: date-time
          example: '2021-08-29 09:12:33'
      type: object

    DeliveryOrderInfo:
      required:
        - driverName
        - remainingTime
        - address
      properties:
        driverName:
          type: string
          example: 'Tom'
        remainingTime:
          type: integer
          example: 20
        address:
          type: string
          example: '555 Seymour St'
      type: object

    PickupOrderInfo:
      required:
        - pickupPlace
        - cookReady
      properties:
        pickupPlace:
          type: string
          example: 'Mcdonald'
        cookReady:
          type: integer
          example: 10
      type: object
